spring:
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa

logging:
  level:
    org.hibernate.type.descriptor.sql: TRACE
    org.flywaydb: DEBUG
